[tool.poetry]
name = "flask-scaffold"
version = "0.1.0"
description = "A scaffold to speed up launching a flask project"
authors = [
    "Weiliang Li <to.be.impressive@gmail.com>"
]

[tool.poetry.dependencies]
python = "^3.7"

# flask
APIFlask = "^1.1.0"
flask = "^2.2.0"
flask-sqlalchemy = "^2.5.1"
flask-migrate = "^3.1.0"

# server
gunicorn = "^20.1.0"
aiohttp = "^3.8.1"
aiohttp_wsgi = "^0.10.0"

# db
psycopg2 = "^2.9.3"
redis = "^4.3.4"
hiredis = "^2.0.0"

[tool.poetry.dev-dependencies]
mypy = "^0.971"
ipython = "^7.34.0"
black = "^22.6"
flake8 = "^5.0.3"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
profile = "black"
